### ISSUE TITLE
RuntimeError on export

### ISSUE THREAD

**Issue by aunoor** [tobi-be/BlenderEdmExporter#2]
I have another issue:
If delete any type of object and do not select another after that, then when we try export to edm we got RuntimeError:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_BlenderEdmExporter\__init__.py", line 39, in execute
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect
```
If select any object after delete, export work without exceptions.

**Comment by tobi-be** [comment]
Hi aunoor,
did you install 1.0.2.? I thought this problem would be solved there

**Comment by aunoor** [comment]
Problem still present in 1.0.2.

**Comment by aunoor** [comment]
Ops, sorry, I installed wrong version. This issue is no more present in 1.0.2.

**Comment by tobi-be** [comment]
fine :) thx
