### ISSUE TITLE
Export error struct.error: ubyte format requires 0 <= number <= 255

### ISSUE THREAD

**Issue by Crash46** [tobi-be/BlenderEdmExporter#24]
Hi Tobi, hitting this error when trying to export an object. I can see we're naming something with more symbols than needed, but not sure where. Happy to provide you the file if needed for investigation.

```
Python: Traceback (most recent call last):
  File "C:\Users\ivanz\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_BlenderEdmExporter\__init__.py", line 54, in execute
    edmmodel.write( self.filepath )
  File "C:\Users\ivanz\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_BlenderEdmExporter\edmexporter.py", line 1354, in write
    r.write(body)
  File "C:\Users\ivanz\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_BlenderEdmExporter\edmexporter.py", line 1137, in write
    writeMesh(file,self.verts,self.tris,exportNormals,exportTangents,True,True,False,exportDamageTangents)
  File "C:\Users\ivanz\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_BlenderEdmExporter\edmexporter.py", line 1044, in writeMesh
    writeUChar(file,v.groups[0])
  File "C:\Users\ivanz\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_BlenderEdmExporter\edmexporter.py", line 21, in writeUChar
    file.write(struct.pack('<B', value))
struct.error: ubyte format requires 0 <= number <= 255

location: <unknown location>:-1

```

**Comment by tobi-be** [comment]
Hi Crash,
Yes the model would be helpful! Or more Informations like how much objects, bones, materials, vertexes, vertexgroups and so on would be also nice. Thx for your feed back

**Comment by Crash46** [comment]
https://www.dropbox.com/s/hhgqk2606a2nego/flag.blend?dl=0

**Comment by Crash46** [comment]
I think it's because I had more than 255 bones, it was a flag animation 🎏
