### ISSUE TITLE
I don't why i make bone and every things

### ISSUE THREAD

**Issue by mrdinoooo** [tobi-be/BlenderEdmExporter#34]
Report: Error
Python: Traceback (most recent call last):
File "C:\Users\lamad\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_BlenderEdmExporter_init_.py", line 42, in execute
edmmodel=createEDMModel()
File "C:\Users\lamad\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_BlenderEdmExporter\edmexporter.py", line 1721, in createEDMModel
AttributeError: 'Bone' object has no attribute 'layers'

also : how to import in dcs if my .edm works in model viewer ???

**Comment by tobi-be** [comment]
You are using the wrong blender version. Only 2.8 -3.x is supported
